import { Inter } from "next/font/google";
import "./globals.css";

import { NextAuthProvider } from "@/lib/NextAuthProvider";
import Menu from "@/app/components/Menu";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body>
          <Menu />
          <div className="pt-16 min-h-screen w-full">
            {children}
          </div>
        </body>
      </NextAuthProvider>
    </html>
  );
}
